# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphMatplotGraphUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,uic
import sys
import matplotlib.pyplot as plt
from mplot3d import Axes3D
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 90, 521, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graph_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.graph_verticalLayout.setObjectName("graph_verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 570, 141, 41))
        #3-3. pushButton 핸들러 연결하기
        self.pushButton.clicked.connect(self.drawGraph)
        #3-4. vertical Layout에 matplotWidget연결하기. 
        self.fig = plt.Figure()
        self.canvas = FigureCanvas(self.fig)
        self.graph_verticalLayout.addWidget(self.canvas)


        #3-5. drawGraph 함수 정읜하기. 
        def drawGraph(self):
            x = np.arange(0,100,1)
            y = np.sin(x)
            ax = self.fig.add_subplot(111)
            ax.piot(x,y,label="sin")
            ax.set_xlabel("x")
            ax.set_xlabel("y")
            ax.set_title("my first sin Graph")
            ax.legend()
            self.canvas.draw()




        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
