# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQT
from matplotlib.figure import Figure



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1245, 1084)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(70, 140, 851, 811))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btn_Generate = QtWidgets.QPushButton(self.tab_4)
        self.btn_Generate.setGeometry(QtCore.QRect(140, 40, 511, 141))
        self.btn_Generate.setObjectName("btn_Generate")
        #self.MplWidgetChange = MplWidgetChange(self.tab_4)
      #  self.MplWidgetChange.setGeometry(QtCore.QRect(0, 210, 821, 591))
       # self.MplWidgetChange.setObjectName("MplWidgetChange")
        self.tabWidget.addTab(self.tab_4, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.tableWidget = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget.setGeometry(QtCore.QRect(-20, 130, 751, 641))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.csvFile = QtWidgets.QTextEdit(self.widget1)
        self.csvFile.setGeometry(QtCore.QRect(130, 50, 271, 41))
        self.csvFile.setObjectName("csvFile")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setGeometry(QtCore.QRect(430, 50, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.widget1, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(930, 220, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setWhatsThis(_translate("Form", "<html><head/><body><p>f</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "MAIN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "LED설정"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "스위치 설정"))
        self.btn_Generate.setText(_translate("Form", "Generate Random Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "전압측정 그래프"))
        self.label.setText(_translate("Form", "CSV 파일명"))
        self.pushButton.setText(_translate("Form", "CLICK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget1), _translate("Form", "Excel 자료가져오기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "기타"))



"""
class MplWidgetChange(QtWidgets):
    def __init__(self, parent = None):
        QtWidgets.__init__(self,parent)
        self.canvas = FigureCanvas(Figure())
        vertical_layout = QVBoxLayout()
        vertical_layout.addWidget(self.canvas)
        self.canvas.axes = self.canvas.figure.add_subplot(111)
        self.setLayout(vertical_layout)


"""


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
